<?php

namespace App\Form;

use App\Entity\BlogComment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BlogCommentType extends AbstractType
{

  public function buildForm(FormBuilderInterface $builder, array $options)
  {
    //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    $builder->add('text', TextareaType::class, [ ]);
  }

  public function configureOptions(OptionsResolver $resolver): void
  {
    $resolver->setDefaults([
      'data_class' => BlogComment::class,
    ]);
  }

}